services:
  app:
    container_name: genai_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=chat_db
    depends_on:
      - mongodb
    networks:
      - genai_net

  mongodb:
    container_name: genai_mongo_db
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - genai_net

volumes:
  mongo_data:

networks:
  genai_net:
